//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice_21
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductComposition
    {
        public int ProductCode { get; set; }
        public int DetailCode { get; set; }
        public int DetailAmount { get; set; }
    
        public virtual Details Details { get; set; }
        public virtual Products Products { get; set; }
    }
}
